version: '3'

services:

  postgres11:
    container_name: postgres11
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:4.13
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@localhost
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5433:80"